In [8]:
import numpy as np
import pandas as pd

namur = pd.read_csv("NamurLake_Data.csv")
Touchwood = pd.read_csv("Touchwood_Data.csv")

In [2]:
namur

,Sampling Timestamp,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Calcium Total,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,Nickel Dissolved,...,Nitrogen Dissolved,Phosphorus Total Dissolved,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,OXYGEN BIOCHEMICAL DEMAND,Site Name,Unit Symbol
0,1999-08-10 10:25:00,NaN,NaN,6130.0,NaN,NaN,NaN,NaN,NaN,NaN,...,258.0,8.0,0.0200,NaN,0.500,6.86,NaN,NaN,NAMUR LAKE,µg/l
1,2000-08-31 09:20:00,NaN,NaN,6470.0,NaN,NaN,NaN,NaN,NaN,NaN,...,340.0,10.0,0.0210,NaN,0.800,7.09,NaN,NaN,NAMUR LAKE,µg/l
2,2001-09-13 10:45:00,NaN,NaN,6280.0,6500.0,NaN,1.100,NaN,0.5820,NaN,...,297.0,11.0,0.0170,NaN,0.680,7.29,NaN,NaN,NAMUR LAKE,µg/l
3,2001-09-13 10:45:00,NaN,16.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
4,2002-10-01 12:00:00,NaN,NaN,6520.0,NaN,NaN,NaN,NaN,NaN,NaN,...,324.0,12.0,0.0300,NaN,0.870,7.12,NaN,NaN,NAMUR LAKE,µg/l
5,2003-08-28 08:55:00,1.600,NaN,6530.0,6500.0,0.300,0.900,0.0100,0.0880,0.700,...,271.0,8.0,0.0180,0.1000,0.650,7.18,NaN,NaN,NAMUR LAKE,µg/l
6,2003-08-28 08:55:00,NaN,13.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
7,2004-08-29 08:45:00,0.250,NaN,6260.0,7120.0,0.453,0.441,0.0069,0.0212,0.560,...,319.0,8.0,0.0170,0.0200,NaN,7.28,NaN,NaN,NAMUR LAKE,µg/l
8,2004-08-29 08:45:00,NaN,3.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
9,2005-08-27 09:58:00,NaN,4.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
10,2005-08-27 09:58:00,0.570,NaN,9600.0,6650.0,0.550,0.555,0.0136,0.0206,0.570,...,258.0,11.0,0.0160,0.0460,0.510,7.43,NaN,NaN,NAMUR LAKE,µg/l
11,2006-08-21 12:10:00,NaN,9.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
12,2006-08-21 12:10:00,NaN,NaN,6270.0,6480.0,NaN,0.497,NaN,0.1920,NaN,...,413.0,6.0,0.0240,NaN,NaN,7.43,NaN,NaN,NAMUR LAKE,µg/l
13,2007-08-21 09:40:00,NaN,15.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
14,2007-08-21 09:40:00,0.226,NaN,6350.0,6500.0,0.290,0.320,0.0154,0.2870,0.562,...,273.0,4.0,0.0160,0.0418,0.510,7.05,NaN,NaN,NAMUR LAKE,µg/l
15,2008-08-27 10:05:00,NaN,6.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
16,2008-08-27 10:05:00,0.467,NaN,6790.0,7100.0,0.343,0.346,0.0115,0.0183,0.724,...,332.0,4.0,0.0120,0.0347,0.320,6.86,NaN,NaN,NAMUR LAKE,µg/l
17,2009-08-19 10:30:00,1.020,NaN,6780.0,6770.0,0.287,0.290,0.0073,0.0381,0.574,...,280.0,4.0,0.0130,0.0538,0.480,7.49,NaN,NaN,NAMUR LAKE,µg/l
18,2009-08-19 10:30:00,NaN,7.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
19,2010-09-03 09:30:00,NaN,6.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
20,2010-09-03 09:30:00,0.364,NaN,7010.0,6920.0,0.262,0.265,0.0022,0.2340,0.524,...,NaN,6.0,0.0140,0.0417,NaN,7.54,NaN,NaN,NAMUR LAKE,µg/l
21,2011-08-30 10:30:00,NaN,5.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
22,2011-08-30 10:30:00,1.650,NaN,7100.0,6300.0,0.305,0.308,0.0097,0.0098,0.548,...,289.0,6.0,0.0100,0.0689,0.690,7.48,NaN,NaN,NAMUR LAKE,µg/l
23,2012-08-30 09:00:00,0.378,NaN,7170.0,7590.0,0.351,0.669,0.0010,0.0209,0.492,...,300.0,4.0,0.0120,0.0591,0.640,7.71,NaN,NaN,NAMUR LAKE,µg/l
24,2012-08-30 09:00:00,NaN,32.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
25,2013-08-26 12:45:00,NaN,10.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
26,2013-08-26 12:45:00,3.680,NaN,6920.0,7460.0,0.285,0.288,0.0080,0.0129,0.593,...,343.0,6.0,0.0140,0.0615,1.530,7.79,NaN,NaN,NAMUR LAKE,µg/l
27,2014-05-26 12:00:00,NaN,NaN,4510.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.6,0.0188,NaN,NaN,7.21,NaN,2.0,NAMUR LAKE,µg/l
28,2014-07-10 12:00:00,2.340,NaN,6140.0,6770.0,0.320,0.330,0.0120,0.0120,0.544,...,NaN,6.5,0.0103,0.0800,NaN,7.46,NaN,2.0,NAMUR LAKE,µg/l
29,2014-07-10 12:00:00,NaN,22.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
30,2014-08-19 14:30:00,1.060,NaN,6210.0,6920.0,0.080,0.050,0.0040,0.0030,0.430,...,307.0,7.0,0.0140,0.0500,0.710,7.50,NaN,NaN,NAMUR LAKE,µg/l
31,2014-08-19 14:30:00,NaN,24.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
32,2014-09-06 12:00:00,NaN,20.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
33,2014-09-06 12:00:00,0.550,NaN,6670.0,7010.0,0.470,0.510,0.0070,0.0230,0.558,...,NaN,34.5,0.0214,0.0600,NaN,7.61,NaN,2.0,NAMUR LAKE,µg/l
34,2015-03-03 12:00:00,NaN,9.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
35,2015-03-03 12:00:00,0.130,NaN,7290.0,8300.0,0.530,0.570,0.0040,0.0130,0.723,...,NaN,21.3,0.0210,0.0400,NaN,7.06,NaN,2.0,NAMUR LAKE,µg/l
36,2015-08-27 16:30:00,NaN,9.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
37,2015-08-27 16:30:00,0.660,NaN,7240.0,7530.0,0.210,0.250,0.0040,0.0150,0.496,...,270.0,5.0,0.0120,0.0400,0.580,7.65,NaN,NaN,NAMUR LAKE,µg/l
38,2016-03-15 12:00:00,NaN,6.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
39,2016-03-15 12:00:00,1.940,NaN,9200.0,11200.0,0.430,0.440,0.0060,0.0060,0.777,...,NaN,10.0,0.0160,0.0500,0.390,7.52,NaN,2.0,NAMUR LAKE,µg/l
40,2016-07-19 12:00:00,0.940,NaN,4940.0,5030.0,0.340,0.340,0.0080,0.0080,0.690,...,NaN,5.0,0.0110,0.0700,0.400,7.48,NaN,NaN,NAMUR LAKE,µg/l
41,2016-07-19 12:00:00,NaN,18.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
42,2016-08-23 10:30:00,0.480,NaN,7130.0,7290.0,0.450,0.540,0.0250,0.9250,0.625,...,346.0,6.0,0.0110,0.0400,0.880,7.75,NaN,NaN,NAMUR LAKE,µg/l
43,2016-08-23 10:30:00,NaN,10.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
44,2016-09-20 12:00:00,NaN,8.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
45,2016-09-20 12:00:00,0.730,NaN,7360.0,7500.0,0.490,0.500,0.0120,0.0250,0.493,...,NaN,11.0,0.0190,0.0300,1.300,7.44,NaN,NaN,NAMUR LAKE,µg/l
46,2017-03-14 12:00:00,NaN,41.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
47,2017-03-14 12:00:00,1.500,NaN,10600.0,10800.0,0.380,0.570,0.0170,0.0500,0.750,...,NaN,14.0,0.0280,0.0700,0.930,7.37,NaN,NaN,NAMUR LAKE,µg/l
48,2017-08-23 08:29:00,0.400,NaN,7930.0,7890.0,0.300,0.290,0.0200,0.0170,0.620,...,283.0,9.0,0.0140,0.0480,0.315,7.64,NaN,NaN,NAMUR LAKE,µg/l
49,2017-08-23 08:29:00,NaN,4.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
50,2020-09-16 08:00:00,NaN,6.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
51,2020-09-16 08:00:00,1.300,NaN,6850.0,7020.0,0.210,0.220,0.0200,0.0180,0.580,...,NaN,5.0,0.0110,0.0440,0.440,6.27,92.3,NaN,NAMUR LAKE,µg/l
52,2021-08-19 15:15:00,NaN,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l
53,2021-08-19 15:15:00,1.300,NaN,7000.0,NaN,0.200,0.210,0.0200,0.0090,0.610,...,NaN,3.0,0.0120,0.0380,0.710,6.42,99.8,NaN,NAMUR LAKE,µg/l
54,2022-09-14 08:50:00,0.700,NaN,7600.0,NaN,0.240,0.230,0.0200,0.0100,0.600,...,NaN,7.2,0.0120,0.0680,0.670,6.41,92.4,NaN,NAMUR LAKE,µg/l
55,2022-09-14 08:50:00,NaN,7.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l

In [3]:
Touchwood

,Unnamed: 0,Sampling Timestamp,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,Nickel Dissolved,Nickel Total Recoverable,Nitrogen Dissolved,Phosphorus Total Dissolved,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,Site Name,Unit Symbol
0,0,2024-07-11 10:30:00,1.2,3.8,34000.0,0.13,0.14,0.02,0.007,0.23,0.24,300.0,3.0,0.0072,0.115,0.10,8.46,NaN,Touchwood Lake,µg/l
1,1,2024-08-20 13:27:00,NaN,NaN,32000.0,NaN,NaN,NaN,NaN,NaN,NaN,310.0,3.0,0.0038,NaN,0.94,8.61,NaN,Touchwood Lake,µg/l
2,2,2024-09-27 11:45:00,NaN,NaN,31000.0,NaN,NaN,NaN,NaN,NaN,NaN,370.0,3.0,0.0130,NaN,2.10,8.33,NaN,Touchwood Lake,µg/l
3,3,2025-02-26 11:00:00,0.4,4.0,34000.0,0.08,0.08,0.02,0.038,0.17,0.22,600.0,10.0,0.0150,0.078,0.12,7.51,NaN,Touchwood Lake,µg/l
4,4,2025-03-25 09:00:00,NaN,NaN,41000.0,NaN,NaN,NaN,NaN,NaN,NaN,420.0,6.9,0.0140,NaN,4.80,7.82,NaN,Touchwood Lake,µg/l
5,5,2025-06-22 12:00:00,NaN,NaN,34000.0,NaN,NaN,NaN,NaN,NaN,NaN,510.0,3.0,0.0110,NaN,2.50,7.52,NaN,Touchwood Lake,µg/l
6,6,2025-07-13 13:45:00,0.7,6.7,34000.0,0.10,0.20,0.02,0.006,0.19,0.30,390.0,5.2,0.0110,0.078,0.13,8.71,NaN,Touchwood Lake,µg/l
7,7,2025-08-10 11:56:00,NaN,NaN,33000.0,NaN,NaN,NaN,NaN,NaN,NaN,390.0,3.0,0.0030,NaN,0.18,8.63,NaN,Touchwood Lake,µg/l
8,8,2025-09-07 11:05:00,NaN,NaN,34000.0,NaN,NaN,NaN,NaN,NaN,NaN,350.0,3.0,0.0092,NaN,3.50,8.52,NaN,Touchwood Lake,µg/l

In [9]:
df = pd.concat([namur, Touchwood])

In [10]:
df = df.drop(columns=["Unnamed: 0"], errors = "ignore")
df["Sampling Timestamp"] = pd.to_datetime(
    df["Sampling Timestamp"], errors="coerce"
)
df = df.sort_values(by="Sampling Timestamp")
df["Distance Group"] = "Far-Fields"
df

,Sampling Timestamp,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Calcium Total,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,Nickel Dissolved,...,Phosphorus Total Dissolved,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,OXYGEN BIOCHEMICAL DEMAND,Site Name,Unit Symbol,Distance Group
0,1999-08-10 10:25:00,NaN,NaN,6130.0,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,0.0200,NaN,0.50,6.86,NaN,NaN,NAMUR LAKE,µg/l,Far-Fields
1,2000-08-31 09:20:00,NaN,NaN,6470.0,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,0.0210,NaN,0.80,7.09,NaN,NaN,NAMUR LAKE,µg/l,Far-Fields
2,2001-09-13 10:45:00,NaN,NaN,6280.0,6500.0,NaN,1.1,NaN,0.582,NaN,...,11.0,0.0170,NaN,0.68,7.29,NaN,NaN,NAMUR LAKE,µg/l,Far-Fields
3,2001-09-13 10:45:00,NaN,16.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAMUR LAKE,µg/l,Far-Fields
4,2002-10-01 12:00:00,NaN,NaN,6520.0,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,0.0300,NaN,0.87,7.12,NaN,NaN,NAMUR LAKE,µg/l,Far-Fields
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2025-03-25 09:00:00,NaN,NaN,41000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,6.9,0.0140,NaN,4.80,7.82,NaN,NaN,Touchwood Lake,µg/l,Far-Fields
5,2025-06-22 12:00:00,NaN,NaN,34000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,0.0110,NaN,2.50,7.52,NaN,NaN,Touchwood Lake,µg/l,Far-Fields
6,2025-07-13 13:45:00,0.7,6.7,34000.0,NaN,0.1,0.2,0.02,0.006,0.19,...,5.2,0.0110,0.078,0.13,8.71,NaN,NaN,Touchwood Lake,µg/l,Far-Fields
7,2025-08-10 11:56:00,NaN,NaN,33000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,0.0030,NaN,0.18,8.63,NaN,NaN,Touchwood Lake,µg/l,Far-Fields
8,2025-09-07 11:05:00,NaN,NaN,34000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,0.0092,NaN,3.50,8.52,NaN,NaN,Touchwood Lake,µg/l,Far-Fields

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 65 entries, 0 to 8
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Sampling Timestamp             65 non-null     datetime64[ns]
 1   Aluminum Dissolved             27 non-null     float64
 2   Aluminum Total Recoverable     29 non-null     float64
 3   Calcium Dissolved              39 non-null     float64
 4   Calcium Total                  24 non-null     float64
 5   Copper Dissolved               27 non-null     float64
 6   Copper Total Recoverable       29 non-null     float64
 7   Lead Dissolved                 27 non-null     float64
 8   Lead Total Recoverable         29 non-null     float64
 9   Nickel Dissolved               27 non-null     float64
 10  Nickel Total Recoverable       29 non-null     float64
 11  Nitrogen Dissolved             27 non-null     float64
 12  Phosphorus Total Dissolved     39 non-null     float64
 13  Phosphorus Total               39 non-null     float64
 14  Vanadium Dissolved             27 non-null     float64
 15  Turbidity                      32 non-null     float64
 16  pH                             39 non-null     float64
 17  Oxygen dissolved % saturation  3 non-null      float64
 18  OXYGEN BIOCHEMICAL DEMAND      5 non-null      float64
 19  Site Name                      65 non-null     object
 20  Unit Symbol                    65 non-null     object
 21  Distance Group                 65 non-null     object
dtypes: datetime64[ns](1), float64(18), object(3)
memory usage: 11.7+ KB

In [12]:
df.describe()

,Sampling Timestamp,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Calcium Total,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,Nickel Dissolved,Nickel Total Recoverable,Nitrogen Dissolved,Phosphorus Total Dissolved,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,OXYGEN BIOCHEMICAL DEMAND
count,65,27.000000,29.000000,39.000000,24.000000,27.000000,29.000000,27.000000,29.000000,27.000000,29.000000,27.00000,39.000000,39.000000,27.000000,32.000000,39.000000,3.000000,5.0
mean,2014-02-20 19:17:01.846153728,0.982778,11.805517,13226.923077,7297.916667,0.310593,0.394793,0.012022,0.093441,0.553074,0.618759,338.62963,7.748718,0.014685,0.056537,0.933594,7.500000,94.833333,2.0
min,1999-08-10 10:25:00,0.130000,3.600000,4510.000000,5030.000000,0.080000,0.050000,0.001000,0.003000,0.170000,0.220000,258.00000,3.000000,0.003000,0.020000,0.100000,6.270000,92.300000,2.0
25%,2008-08-27 10:05:00,0.433500,6.530000,6495.000000,6612.500000,0.225000,0.250000,0.006950,0.010000,0.510000,0.592000,286.00000,4.000000,0.011000,0.040850,0.430000,7.195000,92.350000,2.0
50%,2014-09-06 12:00:00,0.700000,8.700000,7100.000000,7015.000000,0.300000,0.330000,0.011500,0.018300,0.570000,0.620000,319.00000,6.000000,0.014000,0.050000,0.660000,7.480000,92.400000,2.0
75%,2017-08-23 08:29:00,1.300000,15.100000,10100.000000,7507.500000,0.405000,0.510000,0.020000,0.038100,0.622500,0.667000,360.00000,9.800000,0.017500,0.069450,0.892500,7.680000,96.100000,2.0
max,2025-09-07 11:05:00,3.680000,41.300000,41000.000000,11200.000000,0.550000,1.100000,0.025000,0.925000,0.777000,0.920000,600.00000,34.500000,0.030000,0.115000,4.800000,8.710000,99.800000,2.0
std,NaN,0.780876,8.964618,11706.332104,1306.571947,0.131631,0.230019,0.006838,0.201145,0.153833,0.158712,78.21821,5.781498,0.005639,0.021501,1.005715,0.577672,4.301550,0.0

In [ ]:
import matplotlib.pyplot as plt
df.hist(figsize=(20,16))
plt.show()

In [ ]:
import matplotlib.pyplot as plt

chem_cols = [
    "Aluminum Dissolved",
    "Aluminum Total Recoverable",
    "Calcium Dissolved",
    "Calcium Total",
    "Copper Dissolved",
    "Copper Total Recoverable",
    "Lead Dissolved",
    "Lead Total Recoverable",
    "Nickel Dissolved",
    "Nickel Total Recoverable",
    "Nitrogen Dissolved",
    "Phosphorus Total Dissolved",
    "Phosphorus Total",
    "Vanadium Dissolved",
    "Turbidity",
    "pH",
    "Oxygen dissolved % saturation",
    "OXYGEN BIOCHEMICAL DEMAND"
]

fig, axes = plt.subplots(5, 4, figsize=(25,15))
axes = axes.flatten()

for i, col in enumerate(chem_cols):
    axes[i].boxplot(df[col].dropna())
    axes[i].set_title(col)
    axes[i].set_ylabel("Concentration")

plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.dates as mdates

fig, axes = plt.subplots(5, 4, figsize=(25,15))
axes = axes.flatten()

for i, col in enumerate(chem_cols):
    ax = axes[i]
    
    for lake in df["Site Name"].unique():
        lake_data = df[df["Site Name"] == lake]
        
        ax.scatter(
            lake_data["Sampling Timestamp"],
            lake_data[col],
            label=lake
            
        )
       

    ax.xaxis.set_major_locator(mdates.AutoDateLocator(minticks=5))
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
    ax.tick_params(axis='x', rotation=45)
    
    ax.set_title(col)
    ax.set_xlabel("Date")
    ax.set_ylabel("Concentration")

handles, labels = ax.get_legend_handles_labels()
fig.legend(handles, labels, loc="upper right")

plt.tight_layout()
plt.show()

In [ ]:
df.describe()

In [7]:
df.to_csv("FarLakes_Data.csv", index= False)